"""empty message

Revision ID: 04bef0524c01
Revises: 8fe4cc9768bc
Create Date: 2024-08-17 13:50:11.420371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bef0524c01'
down_revision = '8fe4cc9768bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recepies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_recepies',
    sa.Column('recepy_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['recepy_id'], ['recepies.id'], ),
    sa.PrimaryKeyConstraint('recepy_id', 'categoria_id')
    )
    op.create_table('favorite_recepies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recepy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recepy_id'], ['recepies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recepy_id')
    )
    op.create_table('recepies_ingredients',
    sa.Column('recepy_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recepy_id'], ['recepies.id'], ),
    sa.PrimaryKeyConstraint('recepy_id', 'ingredient_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.drop_table('recepies_ingredients')
    op.drop_table('favorite_recepies')
    op.drop_table('categoria_recepies')
    op.drop_table('recepies')
    op.drop_table('ingredients')
    op.drop_table('category')
    # ### end Alembic commands ###
