"""empty message

Revision ID: 598eb9225cfa
Revises: 04bef0524c01
Create Date: 2024-08-19 09:04:31.733492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598eb9225cfa'
down_revision = '04bef0524c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['userName'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userName')

    # ### end Alembic commands ###
